### ISSUE TITLE
Bug Report #6

### ISSUE THREAD

**Issue by humud99** [TimothyLai77/eecs-3311-project#45]
Case #7
Reported By: Humud Abdalla 
Date Reported: March 15, 2023
Program name: VirtualRestaurantAssistant
Release number: Iteration 2
Configurations: Mac OS 64-bit
Report type: Design issue
Can reproduce: yes
Severity: med
Priority:
Problem summary: As a user i'm not able to see vegan or gluten free ingredients.

Problem description: When i order a Veggie patty burger i see the same ingredients as if i were to order a beef burger. The vegan or gluten free ingredients are not distinguished from the regular ingredients.

Suggested fix: For example, when i order a Veggie patty burger you can not show some ingredients and only show the gluten free or vegan ingredients.

Status: Open

Resolution:
Resolved by:

**Comment by Ali7109** [comment]
Thank you for reporting, Humud. 

The fix has been addressed as we mentioned in the User Story, which did not have to do with toppings, but actually to do with Base sandwiches only as all the toppings are vegan. As for the Dietary restrictions for the Base Sandwiches, well those have just been added. In Pull Request #58 . The Feature is also in the latest build of main, ready to pull.

Thank you again for bringin
![dietaryRest](https://user-images.githubusercontent.com/73392864/227400263-6450ef69-7bd8-4502-8524-441c79a3526e.png)
g this report, and please let me know if this fits as per your request. You can also see an attached screenshot of the feature.
