### ISSUE TITLE
Bug report #7

### ISSUE THREAD

**Issue by humud99** [TimothyLai77/eecs-3311-project#46]
Case #7
Reported By: Humud Abdalla
Date Reported: March 15, 2023
Program name: VirtualRestaurantAssistant
Release number: Iteration 2
Configurations: Mac OS 64-bit
Report type: code issue
Can reproduce: yes
Severity: low
Priority:

Problem summary: Don't see the full details of an order from the receipt

Problem description: When i place an order and want to save the receipt in my local disk, the .txt file does not show the full details of the order whereas the receipt in the application does. 

Suggested fix: Add the full details of the order when generating the .txt file

Status: Open

Resolution:
Resolved by:

**Comment by Ali7109** [comment]
Thank you for reporting, Humud. We have prioritized this issue as low however it is a quick fix so I added the required addition.

Now the final txt file receipt should also have topping details, if there were any added. You can see the merged pull request #49  . The Feature is also in the latest build of main, ready to pull.

Thank you again for bringing this report, and please let me know if this fits as per your request. You can also see an attached screenshot of the feature.

![receiptToppings](https://user-images.githubusercontent.com/73392864/225929304-dd121e15-390b-4631-b0cc-d5e1f5c03d14.png)
